version: '3.8'
services:
    client:
        build: ./
        container_name: client
        ports:
            - '3000:3000'
        volumes:
            - ./:/app
            - /app/node_modules
        stdin_open: true
        tty: true
        environment:
            CHOKIDAR_USEPOLLING: 'true'
