version: '3.8'
services:
    client:
        # build: ./ # NOTE: Only works for Dockerfile
        build: # NOTE: Works for files other than Dockerfile
            context: ./
            dockerfile: Dockerfile.dev
        image: jbsdevden/mern-tms-client
        container_name: client
        ports:
            - '3000:3000'
        volumes:
            - ./:/app
            - /app/node_modules
        stdin_open: true
        tty: true
        # environment
        #     CHOKIDAR_USEPOLLING: 'true'

        env_file:
            - ../.env
