version: '3.8'

services:
    client:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile.prod
        image: 'jbsdevden/mern-tms-client:${GITHUB_SHA}'
        container_name: client
        ports:
            - '3000:80'

        env_file:
            - ../.env

    nginx:
        image: nginx:alpine
        build:
            context: ../
            dockerfile: ./docker/Dockerfile.prod
        volumes:
            - ../nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - server
        expose:
            - 80
        ports:
            - 3000:80
