version: '3.8'
services:
    client:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile.dev
        image: jbsdevden/mern-tms-client
        container_name: client
        ports:
            - '3000:3000'
        volumes:
            - ../:/app
            - /app/node_modules
        stdin_open: true
        tty: true

        env_file:
            - ../.env
