name: Release

on:
    workflow_run:
        workflows: ['Integration']
        types:
            - completed

jobs:
    deploy:
        if: github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest

        env:
            DH_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
            DH_PASSWORD: ${{secrets.D_HUB_MERN_TMS_CLIENT_AT}}

        steps:
            - uses: actions/checkout@v3

            - name: Generate env file
              run: |
                  touch .env
                  echo REACT_APP_NODE_ENV = ${{ env.REACT_APP_NODE_ENV }} >> .env
                  echo REACT_APP_BE_URL = ${{ env.REACT_APP_BE_URL }} >> .env
                  cat .env

            - name: Build the client production image
              run: npm run compose:up:prod
            #   run: docker build -t jbsdevden/mern-tms-client .

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{env.DH_USERNAME}}
                  password: ${{env.DH_PASSWORD}}

            - run: docker push jbsdevden/mern-tms-client
